memtrace:
  tracecount: 5000000000
  maxrthtime: 100000
  concurrentmax: 1
  rthcalculatortype: reservoir
  reservoirsize: 1000000
  pinpath: /home/wjx/bin/pin
  pintoolpath: /home/wjx/Workspace/pin-3.17/source/tools/MemTrace2/obj-intel64/MemTrace2.so
  buffersize: 8000
  writethreshold: 15000
perfstat:
  sampletime: 30s
algorithm:
  classify:
    mpkiveryhigh: 10
    hpkiveryhigh: 10
    hpkiverylow: 0.5
    ipcverylow: 0.6
    ipclow: 1.3
    llcmissratehigh: 0.4
    llcapihigh: 0.005
    mrclowest: 0.3
    noncriticalcachesize: 512
    mediumcachesize: 16384
  dcaps:
    maxiteration: 200
    initialstep: 10000
    minstep: 100
    stepreductionratio: 0.8
    initialtemperature: 10000
    temperaturemin: 100
    temperaturereductionratio: 0.8
    k: 1
    probabilitychangescheme: 0.1
    aggregatechangeofoccupancythreshold: 100
kubernetes:
  tokenfile: ""
  cafile: ""
  insecure: false
  host: https://localhost:8443
manager:
  alloccooldown: 1m0s
  allocsquash: 50ms
  changeprocesscountthreshold: 100
  ClassifyAfter: 5s
  targetprograms:
    - perlbench_r_base.ubuntu-m64
    - cpugcc_r_base.ubuntu-m64
    - mcf_r_base.ubuntu-m64
    - omnetpp_r_base.ubuntu-m64
    - cpuxalan_r_base.ubuntu-m64
    - x264_r_base.ubuntu-m64
    - deepsjeng_r_base.ubuntu-m64
    - leela_r_base.ubuntu-m64
    - exchange2_r_base.ubuntu-m64
    - xz_r_base.ubuntu-m64
