memtrace:
    tracecount: 500000000
    maxrthtime: 100000
    concurrentmax: 1
    rthcalculatortype: noUpdate
    reservoirsize: 100000
    pinpath: /home/wjx/bin/pin
    pintoolpath: /home/wjx/Workspace/pin-3.17/source/tools/MemTrace2/obj-intel64/MemTrace2.so
    buffersize: 8000
    writethreshold: 15000
perfstat:
    sampletime: 10s
algorithm:
    classify:
        mpkiveryhigh: 10
        hpkiveryhigh: 10
        hpkiverylow: 0.5
        ipcverylow: 0.6
        ipclow: 1.3
        llcmissratehigh: 0.4
        llcapihigh: 0.005
        mrclowest: 0.3
        noncriticalcachesize: 512
        mediumcachesize: 16384
    dcaps:
        maxiteration: 200
        initialstep: 10000
        minstep: 100
        stepreductionratio: 0.8
        initialtemperature: 10000
        temperaturemin: 100
        temperaturereductionratio: 0.8
        k: 1
        probabilitychangescheme: 0.1
        aggregatechangeofoccupancythreshold: 100
kubernetes:
    tokenfile: ""
    cafile: ""
    insecure: false
    host: https://localhost:8443
manager:
    alloccooldown: 1m0s
    allocsquash: 50ms
    changeprocesscountthreshold: 100
    targetprograms:
      - blackscholes
      - bodytrack
      - canneal
      - dedup
      - facesim
      - ferret
      - fluidanimate
      - freqmine
      - rtview
      - streamcluster
      - swaptions
      - vips
      - x264
