apiVersion: v1
kind: Namespace
metadata:
  name: workload-classifier
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: resource-manager
  namespace: workload-classifier
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resource-manager
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "deployments", "replicasets", "daemonsets", "statefulsets"]
    verbs: ["list", "watch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resource-manager
subjects:
  - kind: ServiceAccount
    name: resource-manager
    namespace: workload-classifier
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: resource-manager
  apiGroup: rbac.authorization.k8s.io
